name: Deploy

on: 
  push:
    branches:
      - main
            
jobs:
  web-deploy:
    name: Deploy
    
    runs-on: windows-latest
    
    steps: 
      - name: Get latest code
        uses: actions/checkout@main      
